version: "2.1"

services:

  postgres:
    image: postgres:9.4-alpine
    volumes: ["postgres-data:/var/lib/postgresql/data"]
    networks: [backing-services]
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: {}

networks:
  backing-services:
    driver: bridge
